<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>비동기작업</title>
</head>
<body>
<h1>Promise - 예외처리: Method Chaining II</h1>
<script>
const promise = new Promise((resolve, reject) => {
  // resolve();
  reject();
  // throw '오류 발생!!!';
})
.then(() => console.log("fulfilled! - 1"))
.then(() => console.log("fulfilled! - 2"))
.catch(() => console.log("catched! - 1"))
.catch(() => console.log("catched! - 2"));

// 오류가 발생하면,
// - promise 체인을 따라가면서 예외 핸들러를 찾아 호출한다.
// - 예외를 처리한 후 체인에 연결된 다음 promise 객체로 fulfill을 통지한다.

console.log("끝!");

</script>
</body>
</html>