<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>비동기작업</title>
</head>
<body>
<h1>Promise - 비동기 작업에서 발생한 예외처리 II</h1>
<script>
const promise = new Promise((resolve, reject) => {
  var xhr = new XMLHttpRequest();
  xhr.onreadystatechange = function() {
    if (xhr.readyState == 4) {
      try {
        console.log(xhr.responseText);
        throw '오류 발생!';
      } catch(err) {
        reject(err);
      }
    }
  };
  xhr.open("GET", "http://localhost:3000/hello", true); 
  xhr.send();
})
.catch(() => console.log("catched!"));

console.log("끝!");

// executor에서 비동기 작업을 실행하는 중에 오류가 발생했을 때,
// 명시적으로 reject() 호출하여 오류가 발생했음을 통지해야 한다.

</script>
</body>
</html>