<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>비동기작업</title>
</head>
<body>
<h1>Promise - 예외처리: catch(onRejection)</h1>
<script>
const promise = new Promise((resolve, reject) => {
  throw '오류 발생!!!';
})
.catch(() => console.log("rejected!"));
// ==> then(undefined, onRejection) 과 동일하다.

console.log("끝!");

</script>
</body>
</html>